"""Staleness checks for docs/frequency-exposure.md.

The document is generated by R/frequency_exposure.R, which takes about ninety
seconds, too slow to re-run on every test pass. What can be checked quickly is
whether the committed document still describes the current project. It can go
stale in two independent ways, and each gets a test:

  the data changed      the frame md5 stamped in the document no longer matches
                        the frame the view serves now
  the model changed     the rating terms printed in the document no longer match
                        FREQUENCY_TERMS in R/frequency.R

Either failure means: re-run R/frequency_exposure.R and commit the result.
"""

from __future__ import annotations

import re
from pathlib import Path

import pytest

from conftest import scalar
from frame import canonical_md5, load_frequency_frame

REPO_ROOT = Path(__file__).resolve().parent.parent
DOCUMENT = REPO_ROOT / "docs" / "frequency-exposure.md"
FREQUENCY_R = REPO_ROOT / "R" / "frequency.R"

REGENERATE = "re-run: Rscript R/frequency_exposure.R"


@pytest.fixture(scope="module")
def document() -> str:
    if not DOCUMENT.exists():
        pytest.fail(f"{DOCUMENT.name} is missing; {REGENERATE}")
    return DOCUMENT.read_text(encoding="utf-8")


def terms_in_r_source() -> list[str]:
    source = FREQUENCY_R.read_text(encoding="utf-8")
    block = re.search(r"FREQUENCY_TERMS\s*<-\s*c\((.*?)\)\s*\n", source, re.S)
    assert block, "could not find FREQUENCY_TERMS in R/frequency.R"
    return re.findall(r'"([^"]+)"', block.group(1))


def test_document_was_generated_from_the_current_frame(staged, document):
    if scalar(staged, "SELECT to_regclass('model.frequency_frame')") is None:
        pytest.skip("model frame not built")

    stamped = re.search(r"frame md5 `([0-9a-f]{32})`", document)
    assert stamped, "document carries no frame md5"

    current = canonical_md5(load_frequency_frame(staged))
    assert stamped.group(1) == current, (
        f"the document describes frame {stamped.group(1)}, the view now serves "
        f"{current}; {REGENERATE}"
    )


def test_document_describes_the_current_rating_terms(document):
    expected = " + ".join(terms_in_r_source())
    assert f"`{expected}`" in document, (
        f"R/frequency.R now fits {expected!r}, which is not what the document "
        f"describes; {REGENERATE}"
    )


def test_the_pricing_model_balances_in_the_document(document):
    """The offset row must reproduce the observed frequency, as the text says."""
    row = re.search(
        r"^\| offset\(log\(exposure\)\) \| pricing model \|.*$", document, re.M
    )
    assert row, "no pricing-model row in the specification table"
    cells = [c.strip() for c in row.group(0).strip("|").split("|")]
    weighted_annual, observed = cells[-2], cells[-1]
    assert weighted_annual == observed, (
        f"pricing model weighted annual frequency {weighted_annual} does not "
        f"balance to observed {observed}"
    )
