"""Checks for docs/model-diagnostics.md and its figures.

The figures are committed PNGs, regenerated byte for byte by R/model_diagnostics.R
on unchanged data. These tests make sure the document still points at figures
that exist, and still describes the current data and cap.
"""

from __future__ import annotations

import re
from pathlib import Path

import pytest

from conftest import scalar
from frame import canonical_md5, load_frequency_frame

REPO_ROOT = Path(__file__).resolve().parent.parent
DOCS = REPO_ROOT / "docs"
DOCUMENT = DOCS / "model-diagnostics.md"
SEVERITY_R = REPO_ROOT / "R" / "severity.R"
REGENERATE = "re-run: Rscript R/model_diagnostics.R"

PNG_SIGNATURE = b"\x89PNG\r\n\x1a\n"


@pytest.fixture(scope="module")
def document() -> str:
    if not DOCUMENT.exists():
        pytest.fail(f"{DOCUMENT.name} is missing; {REGENERATE}")
    return DOCUMENT.read_text(encoding="utf-8")


def test_every_figure_the_document_shows_exists_and_is_a_png(document):
    figures = re.findall(r"!\[[^\]]*\]\(([^)]+\.png)\)", document)
    assert len(figures) == 2, figures
    for relative in figures:
        path = DOCS / relative
        assert path.exists(), f"{relative} is referenced but missing; {REGENERATE}"
        data = path.read_bytes()
        assert data.startswith(PNG_SIGNATURE), f"{relative} is not a PNG"
        assert len(data) > 5_000, f"{relative} is suspiciously small"


def test_document_was_generated_from_the_current_frame(staged, document):
    stamped = re.search(r"frame md5 `([0-9a-f]{32})`", document)
    assert stamped and stamped.group(1) == canonical_md5(load_frequency_frame(staged)), REGENERATE


def test_document_describes_the_current_cap(document):
    cap = re.search(r"^LARGE_LOSS_CAP\s*<-\s*([0-9]+)\s*$", SEVERITY_R.read_text(encoding="utf-8"), re.M)
    assert cap, "no LARGE_LOSS_CAP in R/severity.R"
    assert f"{int(cap.group(1)):,}" in document, REGENERATE


def test_figures_are_tracked_by_git():
    import subprocess

    for name in ("frequency-quantile-residuals.png", "severity-quantile-residuals.png"):
        path = f"docs/figures/{name}"
        tracked = subprocess.run(
            ["git", "ls-files", "--error-unmatch", path], cwd=REPO_ROOT, capture_output=True
        ).returncode == 0
        assert tracked, f"{path} is not tracked by git"
        ignored = subprocess.run(
            ["git", "check-ignore", "-q", "--no-index", path], cwd=REPO_ROOT
        ).returncode == 0
        assert not ignored, f"{path} is ignored by .gitignore"
