# Rating bands for the continuous frequency terms.
#
# Driver age, vehicle age and bonus-malus enter the frequency model as bands
# rather than as linear terms. docs/frequency-banding.md, generated by
# R/frequency_banding.R, shows why each linear term fails and how these
# boundaries were chosen over equal-exposure quantiles.
#
# The boundaries are constants, not quantiles computed when a model is fitted.
# A rate table is a published list of bands; if its boundaries were recomputed
# from whatever data happened to be loaded, a reload could move a driver from one
# rated band to another without anyone deciding it.
#
# Each scheme is a vector of inclusive lower bounds. A band runs from its lower
# bound to one below the next, and the last is open-ended, so the bands are
# contiguous by construction: there is no way to write a gap or an overlap. The
# only failure left is a value below the first bound, and band_of() refuses it.
#
# Density stays log-linear and vehicle power stays as it is decided in the
# banding document; neither is banded here without evidence that it should be.

DRIVER_AGE_LOWER <- c(18, 20, 22, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 80)

VEH_AGE_LOWER <- c(0, 1, 2, 3, 5, 7, 10, 12, 15, 20)

# 50 is the floor of the French bonus-malus scale and holds 63% of exposure; 100 is
# the entry coefficient for a new policyholder. Both get a band of their own
# because they are states of a policy's history rather than points on a scale.
BONUS_MALUS_LOWER <- c(50, 51, 55, 60, 70, 80, 90, 100, 101, 120)

band_labels <- function(lower) {
  upper <- c(lower[-1] - 1, NA)
  ifelse(is.na(upper), paste0(lower, "+"),
         ifelse(upper == lower, as.character(lower), paste0(lower, "-", upper)))
}

# The band containing each value, as an ordered factor whose levels are in band
# order. Refuses anything below the first lower bound rather than returning NA.
band_of <- function(x, lower) {
  if (is.unsorted(lower, strictly = TRUE)) {
    stop("band lower bounds must be strictly increasing", call. = FALSE)
  }
  below <- x < lower[1]
  if (any(below)) {
    stop(sprintf("%d values below the first band bound %s, minimum %s",
                 sum(below), lower[1], min(x)), call. = FALSE)
  }
  labels <- band_labels(lower)
  factor(labels[findInterval(x, lower)], levels = labels)
}

# The bound arguments are referred to through .env on purpose. Inside mutate, a
# bare name resolves to a data column before it resolves to a function argument,
# and the first draft of this function named its arguments veh_age and
# bonus_malus, so band_of(veh_age, veh_age) received the column twice. Tested
# both ways: on the real frame the column is unsorted and band_of()'s
# strictly-increasing check stops it, but on three rows that happened to be in
# order it returned vehicle-age bands of 0-3, 4-19 and 20+, built from the data
# itself, without a word. The check was the only thing between that bug and
# silently wrong bands. .env makes each lookup unambiguous whatever the columns
# are called, and check_bands() verifies the result against the labels.
apply_bands <- function(frame,
                        driver_age_lower = DRIVER_AGE_LOWER,
                        veh_age_lower = VEH_AGE_LOWER,
                        bonus_malus_lower = BONUS_MALUS_LOWER) {
  dplyr::mutate(
    frame,
    driv_age_band    = band_of(driv_age, .env$driver_age_lower),
    veh_age_band     = band_of(veh_age, .env$veh_age_lower),
    bonus_malus_band = band_of(bonus_malus, .env$bonus_malus_lower)
  )
}

# Every band's observed values must lie inside the range its label states.
# Returns the per-band ranges, and stops if any band holds a value outside them.
check_bands <- function(frame, column, band_column, lower) {
  labels <- band_labels(lower)
  upper <- c(lower[-1] - 1, Inf)
  ranges <- do.call(rbind, lapply(seq_along(labels), function(i) {
    values <- frame[[column]][frame[[band_column]] == labels[i]]
    data.frame(band = labels[i], bound_lo = lower[i], bound_hi = upper[i],
               seen_lo = if (length(values)) min(values) else NA,
               seen_hi = if (length(values)) max(values) else NA,
               rows = length(values))
  }))
  bad <- with(ranges, rows > 0 & (seen_lo < bound_lo | seen_hi > bound_hi))
  if (any(bad)) {
    stop(sprintf("%s: bands %s hold values outside their labels", column,
                 paste(ranges$band[bad], collapse = ", ")), call. = FALSE)
  }
  if (sum(ranges$rows) != nrow(frame)) {
    stop(sprintf("%s: %d rows banded, frame has %d", column, sum(ranges$rows), nrow(frame)),
         call. = FALSE)
  }
  ranges
}
