# The frequency model: a Poisson GLM with log(exposure) as an offset.
#
# Every frequency fit in the project goes through fit_frequency(), so the
# exposure term is written once. docs/frequency-exposure.md, generated by
# R/frequency_exposure.R, shows what each of the tempting alternatives does to
# the same data, and why this one is used for pricing even though the data
# rejects its central assumption.
#
# Two facts decide the form.
#
# The offset is what makes the prediction an annual rate. With a log link and an
# offset, the fitted mean is exposure * exp(linear predictor), so exp(linear
# predictor) is claims per policy-year, and a policy priced for a full year is
# priced at exposure = 1. The fitted claims then sum to the observed claims, so
# the exposure-weighted predicted annual frequency balances to the portfolio's
# 36,102 claims over 358,360 policy-years. fit_frequency() checks that.
#
# Exposure may be passed as a prior weight instead, but only with the claim rate
# as the response. glm(claim_nb / exposure ~ ..., weights = exposure) gives the
# same coefficients as the offset to within 1e-7. The error is weights with the
# count as the response. That fits claims per policy rather than per policy-year:
# the exposure-weighted annual frequency comes out 36% low, the fuel relativity
# moves from 1.053 to 0.973, and brand B12 from 1.167 to 0.769. It runs without a
# warning.
#
# Those figures are from the D2-2 analysis, run on linear rating terms.
#
# The data rejects proportionality. Estimated rather than fixed, the coefficient
# on log(exposure) is 0.37 on the linear terms and 0.41 on the banded terms now in
# use, around a hundred standard errors below 1 either way. The offset is kept
# regardless. Exposure here is the part of a year a policy was in force, and a
# policy can end early because it claimed: cancelled, written off, moved to
# another insurer. The data carries no dates or cancellation reasons, so that
# cannot be confirmed or ruled out, but if it happens then exposure is partly an
# outcome, and a model that estimates its coefficient is learning from the
# outcome. At the point of pricing, a policy's eventual exposure is unknown and
# the rate has to be for a full year, so log(exposure) can be a diagnostic but
# not a rating input.

# Area is not in the formula. It is a banding of density, rank correlation 0.976
# with it, so the two together are near-collinear; density carries the finer
# information, and stays a single log-linear slope because its decile
# diagnostics show no curvature to capture.
#
# Driver age, vehicle age and bonus-malus enter as the bands in R/bands.R and
# vehicle power as a factor. docs/frequency-banding.md compares this with linear
# terms and with equal-exposure decile bands on a holdout of risk groups, under a
# rule fixed before fitting; this specification had the lowest holdout deviance,
# and BIC agreed. tests/test_frequency_banding.py fails if these terms stop
# matching the ones that document chose.
FREQUENCY_TERMS <- c(
  "veh_brand", "veh_gas", "region",
  "driv_age_band", "veh_age_band", "bonus_malus_band", "log(density)", "factor(veh_power)"
)

frequency_formula <- function(terms = FREQUENCY_TERMS) {
  stats::as.formula(paste(
    "claim_nb ~", paste(terms, collapse = " + "), "+ offset(log(exposure))"
  ))
}

fit_frequency <- function(frame, terms = FREQUENCY_TERMS) {
  # Band on demand, so every caller gets the same bands from R/bands.R and none
  # has to remember to apply them first.
  if (any(grepl("_band\\b", terms)) && !"driv_age_band" %in% names(frame)) {
    if (!exists("apply_bands", mode = "function")) {
      stop("banded terms need R/bands.R sourced before R/frequency.R", call. = FALSE)
    }
    frame <- apply_bands(frame)
  }

  fit <- stats::glm(frequency_formula(terms), family = stats::poisson(link = "log"),
                    data = frame)

  if (!fit$converged) {
    stop("frequency GLM did not converge in ", fit$iter, " iterations", call. = FALSE)
  }

  # With a log link, an intercept and an offset, the score equation for the
  # intercept forces fitted claims to sum to observed claims. If they do not,
  # the exposure term is not an offset, whatever the formula looks like.
  observed <- sum(frame$claim_nb)
  gap <- abs(sum(stats::fitted(fit)) - observed)
  if (gap > 1e-6 * observed) {
    stop(sprintf("fitted claims %.3f do not balance to observed %d",
                 sum(stats::fitted(fit)), observed), call. = FALSE)
  }

  fit
}

# Claims per policy-year for each row, as if priced for a full year.
annual_frequency <- function(fit, frame) {
  exp(stats::predict(fit, newdata = transform(frame, exposure = 1), type = "link"))
}
