# The severity model: a Gamma GLM with a log link, on priced claims only.
#
# docs/severity-population.md, generated by R/severity_population.R, shows why
# each guard in fit_severity() exists.
#
# There is deliberately no default set of rating terms yet. A single-fold holdout
# comparison of the frequency terms against a constant was decided by one claim
# of 390,742, and across five folds the verdict changed sign three times, so
# nothing here can yet say which terms severity should use. That choice is made
# in D2-6, after large losses are dealt with, and until then every caller has to
# name its terms.

SEVERITY_CLAIM_COLUMNS <- c("claim_key", "claim_amount")

load_severity_frame <- function(con, frequency_frame) {
  frame <- DBI::dbGetQuery(con, "SELECT * FROM model.severity_frame ORDER BY claim_key")
  expected <- DBI::dbGetQuery(con, "SELECT count(*) FROM fact.claim")[[1]]
  if (nrow(frame) != expected) {
    stop(sprintf("severity frame has %d rows, fact.claim has %d", nrow(frame), expected), call. = FALSE)
  }

  # Rating factors are carried over from the frequency frame already loaded,
  # rather than rebuilt from this query's text columns, so a claim gets exactly
  # the factor levels, bands and risk group its policy has in the frequency model.
  # Keys arrive as doubles under bigint = "numeric"; made integers after a
  # lossless check for the same reason as idpol in R/model_frame.R.
  for (key in c("idpol", "claim_key")) {
    if (any(frame[[key]] != trunc(frame[[key]]) | frame[[key]] > .Machine$integer.max)) {
      stop(key, " does not fit losslessly in an R integer", call. = FALSE)
    }
    frame[[key]] <- as.integer(frame[[key]])
  }

  row <- match(frame$idpol, frequency_frame$idpol)
  if (anyNA(row)) {
    stop(sprintf("%d claims have no policy in the frequency frame", sum(is.na(row))), call. = FALSE)
  }
  cbind(frame[SEVERITY_CLAIM_COLUMNS], frequency_frame[row, , drop = FALSE], row.names = NULL)
}

# glm() stops after 25 iterations by default. A Gamma fit on these heavy-tailed
# amounts can need more, and when it runs out glm() returns coefficients with only
# a warning. The limit is raised, and a fit that still has not converged is refused.
SEVERITY_MAX_ITERATIONS <- 100

fit_severity <- function(frame, terms) {
  if (missing(terms)) {
    stop("fit_severity() has no default terms yet; pass them explicitly (character(0) for a constant)",
         call. = FALSE)
  }

  amount <- frame$claim_amount
  # These two checks are the point of this function. A Gamma family rejects a
  # zero with an error, but it never sees a null: glm() drops rows with a missing
  # response before fitting, without saying so. Both are refused here with a count.
  if (anyNA(amount)) {
    stop(sprintf("%d %s no amount. Severity is fitted on priced claims only; ",
                 sum(is.na(amount)), if (sum(is.na(amount)) == 1) "claim has" else "claims have"),
         "build the frame from model.severity_frame rather than from policies.", call. = FALSE)
  }
  if (any(amount <= 0)) {
    stop(sprintf("%d %s a non-positive amount; a Gamma model cannot take it",
                 sum(amount <= 0), if (sum(amount <= 0) == 1) "claim has" else "claims have"), call. = FALSE)
  }

  if (any(grepl("_band\\b", terms)) && !"driv_age_band" %in% names(frame)) {
    frame <- apply_bands(frame)
  }

  rhs <- if (length(terms)) paste(terms, collapse = " + ") else "1"
  fit <- stats::glm(stats::as.formula(paste("claim_amount ~", rhs)),
                    family = stats::Gamma(link = "log"), data = frame,
                    na.action = stats::na.fail,
                    control = stats::glm.control(maxit = SEVERITY_MAX_ITERATIONS))

  if (!fit$converged) {
    stop("severity GLM did not converge in ", SEVERITY_MAX_ITERATIONS, " iterations", call. = FALSE)
  }
  if (stats::nobs(fit) != nrow(frame)) {
    stop(sprintf("severity GLM used %d of %d claims", stats::nobs(fit), nrow(frame)), call. = FALSE)
  }
  # With 26,444 claims, a band can have no claims in a training subset. Its
  # coefficient is then NA, and predict() would treat it as zero with only a
  # warning, pricing that band at the base level.
  aliased <- names(which(is.na(stats::coef(fit))))
  if (length(aliased)) {
    stop("severity GLM has coefficients with no data: ", paste(aliased, collapse = ", "), call. = FALSE)
  }

  fit
}

gamma_unit_deviance <- function(y, mu) 2 * (-log(y / mu) + (y - mu) / mu)
