# The severity model: a Gamma GLM with a log link, on priced claims only.
#
# docs/severity-population.md, generated by R/severity_population.R, shows why
# each guard in fit_severity() exists.
#
# fit_severity() takes its terms explicitly and has no default. On uncapped
# amounts a holdout comparison of the frequency terms against a constant was
# decided by one claim of 390,742 and changed sign across five folds, so every
# analysis names the specification it means.
#
# The pricing severity model is fit_pricing_severity(): claims capped at
# LARGE_LOSS_CAP, rating terms SEVERITY_TERMS, and the capped-off losses restored
# by large_loss_load(). docs/severity-large-losses.md chose those terms under a
# rule fixed before fitting.

SEVERITY_CLAIM_COLUMNS <- c("claim_key", "claim_amount")

load_severity_frame <- function(con, frequency_frame) {
  frame <- DBI::dbGetQuery(con, "SELECT * FROM model.severity_frame ORDER BY claim_key")
  expected <- DBI::dbGetQuery(con, "SELECT count(*) FROM fact.claim")[[1]]
  if (nrow(frame) != expected) {
    stop(sprintf("severity frame has %d rows, fact.claim has %d", nrow(frame), expected), call. = FALSE)
  }

  # Rating factors are carried over from the frequency frame already loaded,
  # rather than rebuilt from this query's text columns, so a claim gets exactly
  # the factor levels, bands and risk group its policy has in the frequency model.
  # Keys arrive as doubles under bigint = "numeric"; made integers after a
  # lossless check for the same reason as idpol in R/model_frame.R.
  for (key in c("idpol", "claim_key")) {
    if (any(frame[[key]] != trunc(frame[[key]]) | frame[[key]] > .Machine$integer.max)) {
      stop(key, " does not fit losslessly in an R integer", call. = FALSE)
    }
    frame[[key]] <- as.integer(frame[[key]])
  }

  row <- match(frame$idpol, frequency_frame$idpol)
  if (anyNA(row)) {
    stop(sprintf("%d claims have no policy in the frequency frame", sum(is.na(row))), call. = FALSE)
  }
  cbind(frame[SEVERITY_CLAIM_COLUMNS], frequency_frame[row, , drop = FALSE], row.names = NULL)
}

# glm() stops after 25 iterations by default. A Gamma fit on these heavy-tailed
# amounts can need more, and when it runs out glm() returns coefficients with only
# a warning. The limit is raised, and a fit that still has not converged is refused.
SEVERITY_MAX_ITERATIONS <- 100

fit_severity <- function(frame, terms) {
  if (missing(terms)) {
    stop("fit_severity() has no default terms; pass them explicitly (character(0) for a constant), ",
         "or use fit_pricing_severity() for the pricing model",
         call. = FALSE)
  }

  amount <- frame$claim_amount
  # These two checks are the point of this function. A Gamma family rejects a
  # zero with an error, but it never sees a null: glm() drops rows with a missing
  # response before fitting, without saying so. Both are refused here with a count.
  if (anyNA(amount)) {
    stop(sprintf("%d %s no amount. Severity is fitted on priced claims only; ",
                 sum(is.na(amount)), if (sum(is.na(amount)) == 1) "claim has" else "claims have"),
         "build the frame from model.severity_frame rather than from policies.", call. = FALSE)
  }
  if (any(amount <= 0)) {
    stop(sprintf("%d %s a non-positive amount; a Gamma model cannot take it",
                 sum(amount <= 0), if (sum(amount <= 0) == 1) "claim has" else "claims have"), call. = FALSE)
  }

  if (any(grepl("_band\\b", terms)) && !"driv_age_band" %in% names(frame)) {
    frame <- apply_bands(frame)
  }

  rhs <- if (length(terms)) paste(terms, collapse = " + ") else "1"
  fit <- stats::glm(stats::as.formula(paste("claim_amount ~", rhs)),
                    family = stats::Gamma(link = "log"), data = frame,
                    na.action = stats::na.fail,
                    control = stats::glm.control(maxit = SEVERITY_MAX_ITERATIONS))

  if (!fit$converged) {
    stop("severity GLM did not converge in ", SEVERITY_MAX_ITERATIONS, " iterations", call. = FALSE)
  }
  if (stats::nobs(fit) != nrow(frame)) {
    stop(sprintf("severity GLM used %d of %d claims", stats::nobs(fit), nrow(frame)), call. = FALSE)
  }
  # With 26,444 claims, a band can have no claims in a training subset. Its
  # coefficient is then NA, and predict() would treat it as zero with only a
  # warning, pricing that band at the base level.
  aliased <- names(which(is.na(stats::coef(fit))))
  if (length(aliased)) {
    stop("severity GLM has coefficients with no data: ", paste(aliased, collapse = ", "), call. = FALSE)
  }

  fit
}

gamma_unit_deviance <- function(y, mu) 2 * (-log(y / mu) + (y - mu) / mu)

# ---------------------------------------------------------------------------
# Large losses
# ---------------------------------------------------------------------------
#
# Claims are capped, not dropped. Dropping a claim above the threshold throws away
# the part of it below the threshold too: at the 99.5th percentile, dropping loses
# 33.0% of recorded losses where capping sets aside 25.3%. The part set aside is
# added back as a flat load on the capped severity. docs/severity-large-losses.md,
# generated by R/severity_large_losses.R, measures the threshold and tests whether
# a flat load is defensible.
#
# The cap is a constant, like the rating bands, so that reloading data cannot move
# it silently. It is the 99.5th percentile of the 26,444 priced claim amounts under
# R's default quantile definition (type 7, linear interpolation, the same as
# Postgres percentile_cont), rounded to a whole unit. The nine R definitions range
# from 34,375 to 34,739 on this data, so the definition is part of the number.
LARGE_LOSS_CAP <- 34377

# Replaces claim_amount with the capped amount and keeps the original beside it,
# so a frame shows whether it has been capped, and refuses to cap twice.
cap_claims <- function(frame, cap = LARGE_LOSS_CAP) {
  if ("claim_amount_uncapped" %in% names(frame)) {
    stop("these claims are already capped", call. = FALSE)
  }
  frame$claim_amount_uncapped <- frame$claim_amount
  frame$claim_excess <- pmax(frame$claim_amount - cap, 0)
  frame$claim_amount <- pmin(frame$claim_amount, cap)
  frame
}

# The factor that restores the losses capping set aside: recorded total over
# capped total, applied to capped severity.
large_loss_load <- function(frame, cap = LARGE_LOSS_CAP) {
  amount <- if ("claim_amount_uncapped" %in% names(frame)) frame$claim_amount_uncapped else frame$claim_amount
  sum(amount) / sum(pmin(amount, cap))
}

# The severity terms, chosen on capped amounts. Over the five risk-group folds the
# frequency terms beat a constant by 41.0 of total out-of-fold Gamma deviance and
# in four folds of five, under a rule written into R/severity_large_losses.R before
# it was run. The margin is small, 0.13%. tests/test_severity_large_losses.py
# fails if these terms stop matching the ones that document chose.
SEVERITY_TERMS <- c(
  "veh_brand", "veh_gas", "region",
  "driv_age_band", "veh_age_band", "bonus_malus_band", "log(density)", "factor(veh_power)"
)

# Capped severity for pricing. Predictions are of capped amounts; multiply by
# large_loss_load() for the expected full cost of a claim.
fit_pricing_severity <- function(frame) {
  fit_severity(cap_claims(frame), SEVERITY_TERMS)
}
